name: Verify Fix

on:
  push:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: pytest -q
      - name: Success - Sentinel fix verified
        run: echo "✅ All tests pass! Sentinel fix was successful."
